console.log(' this is a Exercise 1 >>')
let challenge = '30 Days Of JavaScript';
console.log(challenge);
console.log(challenge.length);
console.log(challenge.toUpperCase());
console.log(challenge.toLowerCase());
console.log(challenge.substr(2));
console.log(challenge.substring(2));
console.log(challenge.includes('Script'));
console.log(challenge.split(""));
console.log(challenge.split());
let company = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon';
console.log(company.split(""));
console.log(challenge.replace('JavaScript','Python'));
console.log(company.charAt(15));
console.log(company.charCodeAt());
console.log(challenge. indexOf("a"));
console.log(challenge. lastIndexOf("a"));
let word = 'You cannot end a sentence with because because because is a conjunction';
console.log(word.indexOf('because'));
console.log(word.lastIndexOf("because"));
console.log(word.search("because"));
console.log(challenge.trim());
console.log(challenge.startsWith('3'));
console.log(challenge.endsWith('t'));
console.log(challenge.match('a'));
let string1 = '30 Days of';
let string2 = 'JavaScript';
console.log(string1.concat(string2));
console.log(challenge.repeat(2));
// end of Exercise one;
